### PR TITLE
Relaxations+OPRmax option to make turbofan better behaved in trade studies

### PR DESCRIPTION
**Pull request by 1ozturkbe**
I have been making some changes to make the model (relaxing all of the energy balance relations) since in my intuition these should always be tight when posed as signomial inequalities instead of equalities. Also added an OPRmax variable so to inject some realism to the tests.

### CODE REVIEW

**Comment by 1ozturkbe** [comment]
add to whitelist

**Comment by 1ozturkbe** [comment]
@mayork the effect of the constraint relaxations to the models is minimal, and I have added TCS warnings and done diffs to make sure. Please confirm that the OPRmax additions to the engines (32 for 73 class, and 40 for GE90) are fine. Thanks!

**Comment by 1ozturkbe** [comment]
Wait, I'm confused as to what you are referring to, since the current formulation has the shaft power balances as inequalities.

**Comment by mayork** [comment]
Yeah that’s my
Bad I’m looking at this on my phone and got looking at the wrong commit. Looked at the right thing now. Very impressive how few equalities are needed now, I love it.

Should’ve thought up the relaxed thing a few months earlier. Would have saved a lot of time on this model I think lol.

**Comment by 1ozturkbe** [comment]
Haha np. Thanks for the quick review @mayork. Merging.

**Pull request merged**
